name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      SHELL: /bin/bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install all the dependencies
        run: pip3 install -r requirements.txt

      - name: Build the project
        run: ablog clean && ablog build

      - name: Setup Github config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Deploy to Github pages
        run: |
          ablog deploy -g tanayseven --github-token ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.19.0

      - name: Run lighthouse performance
        run: |
          lighthouse-badges --version || npm i -g lighthouse-badges
          lighthouse-badges --urls https://tanayseven.com/ https://tanayseven.com/blog -o test_results

      - name: Install Netlify CLI
        run: npm install netlify-cli -g

      - name: Publish the performance badges to Netlify
        run: netlify deploy --auth=${{ secrets.NETLIFY_TOKEN }} --dir=test_results/ --site=tanayseven-badges-personal-website.netlify.app
